name: build
channels: !!python/tuple
- !!python/unicode
  'defaults'
dependencies:
- jpeg=8d=vc9_2
- libpng=1.6.27=vc9_0
- libtiff=4.0.6=vc9_2
- mkl=11.3.3=1
- numpy=1.11.2=py27_0
- openssl=1.0.2k=vc9_0
- pip=9.0.1=py27_1
- pyqt=4.11.4=py27_7
- python=2.7.13=0
- pywin32=220=py27_2
- qt=4.8.7=vc9_9
- setuptools=27.2.0=py27_1
- sip=4.18=py27_0
- vs2008_runtime=9.00.30729.1=2
- vtk=6.3.0=py27_1
- wheel=0.29.0=py27_0
- zlib=1.2.8=vc9_3
- pip:
  - future==0.16.0
  - pyinstaller==3.2.1

